version: 1

linters:
  enable:
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - errcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/euclidstellar/testtt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m